### ISSUE TITLE
masterha_check_repl occur "There is no alive server. We can't do failover" error

### ISSUE THREAD

**Issue by scuhzq** [yoshinorim/mha4mysql-manager#89] opened 2017-12-28 09:44 UTC
When I use  masterha_check_repl --conf=/usr/local/mha/app.cnf to check master-slave replication status， it occurs an error.
But the ssh and masterha_secondary_check execute success，and I use the user and repl_user configure in app.cnf can success access mysql.

 [error][/usr/local/share/perl5/MHA/ServerManager.pm, ln188] There is no alive server. We can't do failover
[error][/usr/local/share/perl5/MHA/MasterMonitor.pm, ln427] Error happened on checking configurations.  at /usr/local/share/perl5/MHA/MasterMonitor.pm line 329
[error][/usr/local/share/perl5/MHA/MasterMonitor.pm, ln525] Error happened on monitoring servers.

**Comment by scuhzq** [comment] 2017-12-28 09:47
My mha version is the latest from the source code build.

**Comment by peng19832** [comment] 2017-12-29 01:42
![1514511707 1](https://user-images.githubusercontent.com/9590209/34427391-97424bd8-ec7c-11e7-8171-ba84bb1299e6.jpg)

**Comment by peng19832** [comment] 2017-12-29 01:45
![image](https://user-images.githubusercontent.com/9590209/34427424-00362902-ec7d-11e7-8216-4d5237eed20e.png)

**Comment by scuhzq** [comment] 2017-12-31 18:18
thanks for you reply, this works well.

**Comment by grypyrg** [comment] 2018-01-17 23:44
Duplicate of #61

**Closed by grypyrg** 2018-01-17 23:44 UTC
